"""create matakuliah table

Revision ID: c40a9515c0bf
Revises: 
Create Date: 2025-12-08 00:35:27.454372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40a9515c0bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matakuliah',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode_mk', sa.Text(), nullable=False),
    sa.Column('nama_mk', sa.Text(), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_mk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matakuliah')
    # ### end Alembic commands ###
